name: Update Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run update-images.py
        run: |
          scripts/update-images.py
          for distro in ubuntu debian; do
            cat "$distro".json | jq -S > "$distro"/images.json
            rm "$distro".json
          done
          if [[ -z $(git status -s) ]]; then
            echo "Images up to date"
            exit 0
          else
            echo "New image"
            git diff
            git config user.name github-actions
            git config user.email github-actions@github.com
            branchname="update-images-$(date +%F)"
            git checkout -b "${branchname}"
            git add debian/images.json
            git add ubuntu/images.json
            git commit -m "Update images: $(date +%F)"
            git push origin "${branchname}"
            gh pr create -B main -H "${branchname}" \
              --title 'Bump images.json' \
              --body 'PR generated using scripts/update-images.py'
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
